### ISSUE TITLE
Error happens when runing your codes according to your instruction

### ISSUE THREAD

**Issue by wdmwhh** [TomVeniat/MNTDP#3]
Hi, Tom Veniat. Thanks for showing the great work.
`ModuleNotFoundError: No module named 'supernets'`
I try hard to find "supernets", but it seems to be absent.

**Comment by zackschen** [comment]
> Hi, Tom Veniat. Thanks for showing the great work.
> `ModuleNotFoundError: No module named 'supernets'`
> I try hard to find "supernets", but it seems to be absent.

I meet this, too. And it seems there is no test_debug.yaml.

**Comment by TomVeniat** [comment]
Hi,

Thank you for raising this issue. I'm working on a fix for the dependencies and updated instructions on how to run the project. 
I'll post an update here as soon as it's done!

**Comment by TomVeniat** [comment]
Hi, 
You can now find the updated README and `requirements.txt` on the `dev` branch.
I need to do some more testing before merging into master but it should be functional as-is.
